[package]
name = "day_03"
version = "0.1.0"
authors = ["Sander Vervaeke <sander_vervaeke@outlook.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
